name: JadedSync
version: '${project.version}'
main: net.jadedmc.jadedsync.JadedSyncBukkitPlugin
api-version: '1.13'
authors: [ JadedMC ]
website: https://www.jadedmc.net

softdepend: [ CloudNet-Bridge, PlaceholderAPI ]

commands:
  instance:
    description: View and control Server instances.
    usage: /<command>
    permission: jadedsync.admin
  jadedsync:
    description: Main JadedSync command.
    usage: /<command>
    permission: jadedsync.admin
    aliases: [ js ]