name: JadedSync
version: '1.0'
main: net.jadedmc.jadedsync.JadedSyncBukkitPlugin
api-version: '1.13'
authors: [ JadedMC ]
website: https://www.jadedmc.net

commands:
  instance:
    description: View and control Server instances.
    usage: /<command>
    permission: jadedsync.admin